// Generated by gencpp from file fs_msgs/FinishedSignal.msg
// DO NOT EDIT!


#ifndef FS_MSGS_MESSAGE_FINISHEDSIGNAL_H
#define FS_MSGS_MESSAGE_FINISHEDSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fs_msgs
{
template <class ContainerAllocator>
struct FinishedSignal_
{
  typedef FinishedSignal_<ContainerAllocator> Type;

  FinishedSignal_()
    : header()
    , placeholder(false)  {
    }
  FinishedSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , placeholder(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _placeholder_type;
  _placeholder_type placeholder;





  typedef boost::shared_ptr< ::fs_msgs::FinishedSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fs_msgs::FinishedSignal_<ContainerAllocator> const> ConstPtr;

}; // struct FinishedSignal_

typedef ::fs_msgs::FinishedSignal_<std::allocator<void> > FinishedSignal;

typedef boost::shared_ptr< ::fs_msgs::FinishedSignal > FinishedSignalPtr;
typedef boost::shared_ptr< ::fs_msgs::FinishedSignal const> FinishedSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fs_msgs::FinishedSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fs_msgs::FinishedSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fs_msgs::FinishedSignal_<ContainerAllocator1> & lhs, const ::fs_msgs::FinishedSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.placeholder == rhs.placeholder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fs_msgs::FinishedSignal_<ContainerAllocator1> & lhs, const ::fs_msgs::FinishedSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::FinishedSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::FinishedSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::FinishedSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fadad42372ab12322143ef83bb4835a";
  }

  static const char* value(const ::fs_msgs::FinishedSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fadad42372ab123ULL;
  static const uint64_t static_value2 = 0x22143ef83bb4835aULL;
};

template<class ContainerAllocator>
struct DataType< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fs_msgs/FinishedSignal";
  }

  static const char* value(const ::fs_msgs::FinishedSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool placeholder\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fs_msgs::FinishedSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.placeholder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FinishedSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fs_msgs::FinishedSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fs_msgs::FinishedSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "placeholder: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.placeholder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FS_MSGS_MESSAGE_FINISHEDSIGNAL_H
