// Generated by gencpp from file fs_msgs/GoSignal.msg
// DO NOT EDIT!


#ifndef FS_MSGS_MESSAGE_GOSIGNAL_H
#define FS_MSGS_MESSAGE_GOSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fs_msgs
{
template <class ContainerAllocator>
struct GoSignal_
{
  typedef GoSignal_<ContainerAllocator> Type;

  GoSignal_()
    : header()
    , mission()
    , track()  {
    }
  GoSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mission(_alloc)
    , track(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_type;
  _mission_type mission;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _track_type;
  _track_type track;





  typedef boost::shared_ptr< ::fs_msgs::GoSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fs_msgs::GoSignal_<ContainerAllocator> const> ConstPtr;

}; // struct GoSignal_

typedef ::fs_msgs::GoSignal_<std::allocator<void> > GoSignal;

typedef boost::shared_ptr< ::fs_msgs::GoSignal > GoSignalPtr;
typedef boost::shared_ptr< ::fs_msgs::GoSignal const> GoSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fs_msgs::GoSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fs_msgs::GoSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fs_msgs::GoSignal_<ContainerAllocator1> & lhs, const ::fs_msgs::GoSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mission == rhs.mission &&
    lhs.track == rhs.track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fs_msgs::GoSignal_<ContainerAllocator1> & lhs, const ::fs_msgs::GoSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::GoSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::GoSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::GoSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::GoSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::GoSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::GoSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fs_msgs::GoSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1901c640b21e17abe7d6ab0e2bf50a8a";
  }

  static const char* value(const ::fs_msgs::GoSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1901c640b21e17abULL;
  static const uint64_t static_value2 = 0xe7d6ab0e2bf50a8aULL;
};

template<class ContainerAllocator>
struct DataType< ::fs_msgs::GoSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fs_msgs/GoSignal";
  }

  static const char* value(const ::fs_msgs::GoSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fs_msgs::GoSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string mission\n"
"string track\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fs_msgs::GoSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fs_msgs::GoSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mission);
      stream.next(m.track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fs_msgs::GoSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fs_msgs::GoSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mission: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission);
    s << indent << "track: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FS_MSGS_MESSAGE_GOSIGNAL_H
