// Generated by gencpp from file fs_msgs/Reset.msg
// DO NOT EDIT!


#ifndef FS_MSGS_MESSAGE_RESET_H
#define FS_MSGS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <fs_msgs/ResetRequest.h>
#include <fs_msgs/ResetResponse.h>


namespace fs_msgs
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace fs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fs_msgs::Reset > {
  static const char* value()
  {
    return "79b3eea4e90fd67af16afc9085f08e12";
  }

  static const char* value(const ::fs_msgs::Reset&) { return value(); }
};

template<>
struct DataType< ::fs_msgs::Reset > {
  static const char* value()
  {
    return "fs_msgs/Reset";
  }

  static const char* value(const ::fs_msgs::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::fs_msgs::ResetRequest> should match
// service_traits::MD5Sum< ::fs_msgs::Reset >
template<>
struct MD5Sum< ::fs_msgs::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fs_msgs::Reset >::value();
  }
  static const char* value(const ::fs_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fs_msgs::ResetRequest> should match
// service_traits::DataType< ::fs_msgs::Reset >
template<>
struct DataType< ::fs_msgs::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::fs_msgs::Reset >::value();
  }
  static const char* value(const ::fs_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fs_msgs::ResetResponse> should match
// service_traits::MD5Sum< ::fs_msgs::Reset >
template<>
struct MD5Sum< ::fs_msgs::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fs_msgs::Reset >::value();
  }
  static const char* value(const ::fs_msgs::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fs_msgs::ResetResponse> should match
// service_traits::DataType< ::fs_msgs::Reset >
template<>
struct DataType< ::fs_msgs::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::fs_msgs::Reset >::value();
  }
  static const char* value(const ::fs_msgs::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FS_MSGS_MESSAGE_RESET_H
